spring:
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    cache:
      channel:
        checkout-timeout: 5000
        # 开启消息监视功能
    publisher-returns: true    # 开启消息未到达的确认
    publisher-confirm-type: correlated  # 开启消息到达的确认
server:
  port: 8081
