# 项目启动端口
server:
    port: 8080

# Spring配置
spring:
    application:
        name: live-home  # 项目启动名字
    # 数据源配置
    datasource:
        username: root
        password: huangxiaodong
        url: jdbc:mysql://rrow.icu:3306/live?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            max-active: 20
            min-idle: 5
            validation-query: select x
            initial-size: 3
            max-wait: 5000
            stat-view-servlet:
                #                login-username: root
                #                login-password: 123456
                allow:
                deny:
                url-pattern: /druid/*
                enabled: true  #启用数据源监控
    redis:
        host: rrow.icu
        port: 6379
        password: fuckyouredis01
        database: 15

# 配置mybatisplus，这里即使不配置也会自动帮我们扫包
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true

swagger3:
    base-package: com.study.controller
    name: cddd
    url: https://www.baidu.com
    email: xxxxx@qq.com
    title: 房屋网管理系统接口
    description: 实现房屋网管理系统的所有接口
    license: xxx
    license-url: https://www.baidu.com
    terms-of-service-url: https://www.baidu.com






