server:
    port: 8081
spring:
    application:
        name: eureka-client
eureka:
    client:
        service-url:
            defalutZone : http://localhost:8761/eureka/
        register-with-eureka: true     # 往eureka注册
        fetch-registry: true        # 拉去服务器列表到本地
        registry-fetch-interval-seconds: 5      # 拉取间隔
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5   # 实例续约的周期