server:
    port: 8762      # \u6E90\u7801\u5B9A\u6B7B\u4E86
spring:
    application:
        name: eruka-server
eureka:
    client:         # eureka.server\u4F1A\u81EA\u5DF1\u6CE8\u518C\u81EA\u5DF1
        service-url:
            defalutZone: http://peer1:8761/eureka,http://peer3:8763/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: peer2
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5   # \u5B9E\u4F8B\u7EED\u7EA6\u7684\u5468\u671F

