spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    cache:
      channel:
        checkout-timeout: 5000
    listener:
      simple:
        acknowledge-mode: manual    # 开启手动签收
#      direct:
#        acknowledge-mode: manual    # 设置直连模式手动签收

  redis:
    port: 6379
    host: 127.0.0.1
    database: 15
    connect-timeout: 5000