server:
    port: 8081
spring:
    application:
        name: nacos-discovery-client-b
    cloud:
        nacos:
            server-addr: rrow.icu:8848      # \u5F80\u54EA\u91CC\u6CE8\u518C\u81EA\u5DF1
            discovery:
                username: nacos
                password: nacos
                namespace: bacfdfb1-18ea-471f-8c2d-a01ee82e82ab     # \u8FD9\u91CC\u5199\u547D\u540D\u7A7A\u95F4\u7684id
                group: DEV-A-GROUP
